name: CI/CD Deploy MERN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: yourdockerhubusername/mern-frontend:latest

    - name: Build & Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: yourdockerhubusername/mern-backend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull yourdockerhubusername/mern-frontend:latest
          docker pull yourdockerhubusername/mern-backend:latest

          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 80:80 yourdockerhubusername/mern-frontend:latest

          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 8000:8000 yourdockerhubusername/mern-backend:latest
