name: CI/CD Deploy MERN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: lautee/luvowear-frontend:latest
          build-args: |
            VITE_BACKEND_URL=http://3.106.252.221:8000
            VITE_PAYPAL_CLIENT_ID=AbwCUoGWf7zPDsCJ9Wx6hLaWi9OPML1l2AZE1lWONatap_K9wCwDbwwO-ysiEn-TPiysR3qd15olR0Kf

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: lautee/luvowear-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull lautee/luvowear-frontend:latest
            docker pull lautee/luvowear-backend:latest

            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:80 lautee/luvowear-frontend:latest

            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend --env-file ./backend/.env -p 8000:8000 lautee/luvowear-backend:latest
