name: CI/CD Deploy MERN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: lautee/luvowear-frontend:latest
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: lautee/luvowear-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker image prune -af || true    

            docker pull lautee/luvowear-backend:latest
            docker network create luvowear-net || true
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend --network luvowear-net --env-file ~/backend/.env -p 8000:8000 lautee/luvowear-backend:latest


            docker pull lautee/luvowear-frontend:latest 
            rm -rf /tmp/frontend_build 
            docker create --name frontend lautee/luvowear-frontend:latest
            docker cp frontend:/usr/share/nginx/html /tmp/frontend_build
            docker rm frontend || true

            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /tmp/frontend_build/* /usr/share/nginx/html/
            sudo systemctl restart nginx
